name: Deploy-Pipeline

on:
  push:
    branches: [ "main" ]


jobs:
  build_and_push_docker:
    # Use a clearer job name
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      # This action securely logs into Docker Hub using secrets
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push Docker image
      # This action handles the build (using the Dockerfile in ./backendfile) and the push
      uses: docker/build-push-action@v5
      with:
        context: ./backendfile  # <-- Tells Docker to look in the 'backendfile' folder for the Dockerfile
        push: true
        tags: hamza5245/backendgithub:v1.0
